apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
  namespace: pks-system
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9978'

spec:
  selector:
    app: telegraf
  type: NodePort
  ports:
    - port: 9978
      targetPort: 9978
      nodePort: 31000
