{
 "title": "PKS Deployment",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_node_info, cluster_name)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_deployment_created{cluster_name=~\"$cluster\"}, namespace)"
   },
   {
    "name": "deployment",
    "query": "label_values(kube_deployment_created{cluster_name=~\"$cluster\", namespace=~\"$namespace\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment Replicas - Desired",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Up-to-date",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Deployments by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_deployment_created{cluster_name=~\"$cluster\", namespace=~\"$namespace\", deployment=~\"$deployment\"}) by (cluster_name, namespace, deployment)",
     "legendFormat": "{{deployment}}/{{namespace}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Replicas per Deployment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pks_kube_deployment_status_replicas_available_gauge{cluster=~\"$cluster\", namespace=~\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "available - {{deployment}}/{{namespace}}/{{cluster}}"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{cluster_name=~\"$cluster\", namespace=~\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "unavailable - {{deployment}}/{{namespace}}/{{cluster_name}}"
    },
    {
     "expr": "kube_deployment_status_replicas_updated{cluster_name=~\"$cluster\", namespace=~\"$namespace\", deployment=~\"$deployment\"}",
     "legendFormat": "updated - {{deployment}}/{{namespace}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Generations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_observed_generation"
    }
   ]
  }
 ]
}