{
 "title": "PKS Namespace",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_node_info, cluster_name)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info,namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Count By Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_start_time{cluster_name=~\"$cluster\"}) by (cluster_name)",
     "legendFormat": "{{namespace}} - {{cluster_name}}"
    }
   ]
  },
  {
   "title": "Pod Container Count By Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{cluster_name=~\"$cluster\",namespace=~\"$namespace\"}) by (cluster_name, namespace)",
     "legendFormat": "{{namespace}} - {{cluster_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{cluster_name=~\"$cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} - {{cluster_name}}"
    }
   ]
  }
 ]
}