{
 "title": "PKS Node",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_node_info, cluster_name)"
   },
   {
    "name": "node",
    "query": "label_values(kube_node_info{cluster_name=~\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kubernetes_node_memory_working_set_bytes{cluster_name=~\"$cluster\",node_name=~\"$node\"} / kube_node_status_capacity_memory_bytes{cluster_name=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "{{cluster_name}}/{{node_name}}"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "CPU Utilization by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})",
     "legendFormat": "{{cluster_name}}/{{node_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage Rate by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "kubernetes_node_cpu_usage_nanocores{cluster_name=~\"$cluster\",node_name=~\"$node\"}",
     "legendFormat": "{{cluster_name}}/{{node_name}}"
    }
   ]
  },
  {
   "title": "Pod Resources Allocatable vs Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_allocatable_pods{cluster_name=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "allocatable_pod_res - {{cluster_name}}/{{node}}"
    },
    {
     "expr": "kube_node_status_capacity_pods{cluster_name=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "capacity_pod_res - {{cluster_name}}/{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "kubernetes_node_memory_usage_bytes{cluster_name=~\"$cluster\",node_name=~\"$node\"} / kube_node_status_capacity_memory_bytes{cluster_name=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU Allocatable vs Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_allocatable_cpu_cores{cluster_name=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "allocatable_core - {{cluster_name}}/{{node}}"
    },
    {
     "expr": "kube_node_status_capacity_cpu_cores{cluster_name=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "capacity_core - {{cluster_name}}/{{node}}"
    }
   ]
  },
  {
   "title": "Bytes Transferred Rate By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "rate(kubernetes_node_network_tx_bytes{cluster_name=~\"$cluster\",node_name=~\"$node\"}[10m])",
     "legendFormat": "{{cluster_name}}/{{node_name}}"
    }
   ]
  },
  {
   "title": "Memory Allocatable vs Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_allocatable_memory_bytes{cluster_name=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "allocatable_mem - {{cluster}}/{{node}}"
    },
    {
     "expr": "kube_node_status_capacity_memory_bytes{cluster_name=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "capacity_mem - {{cluster_name}}/{{node}}"
    }
   ]
  },
  {
   "title": "Bytes Received Rate By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "rate(kubernetes_node_network_rx_bytes{cluster_name=~\"$cluster\",node_name=~\"$node\"}[10m])",
     "legendFormat": "{{cluster_name}}/{{node_name}}"
    }
   ]
  },
  {
   "title": "File System - Available Storage by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 27 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_filesystem_limit{cluster=~\"$cluster\",nodename=~\"$node\"} - pks_heapster_node_filesystem_usage{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": " {{resource_id}} - {{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Networking Errors By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "rate(kubernetes_node_network_rx_errors{cluster_name=~\"$cluster\",node_name=~\"$node\"}[10m])",
     "legendFormat": "rx_err - {{cluster_name}}/{{node_name}}"
    },
    {
     "expr": "rate(kubernetes_node_network_tx_errors{cluster_name=~\"$cluster\",node_name=~\"$node\"}[10m])",
     "legendFormat": "tx_err - {{cluster_name}}/{{node_name}}"
    }
   ]
  },
  {
   "title": "File System Usage By Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 32 },
   "yaxes": [
    { "format": "bytes", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_filesystem_usage{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": " {{resource_id}} - {{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk IO Write Rate by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pks_heapster_node_disk_io_write_bytes{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])) by (cluster, nodename)",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "File System - Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "pks_heapster_node_filesystem_usage{cluster=~\"$cluster\",nodename=~\"$node\"} / pks_heapster_node_filesystem_limit{cluster=~\"$cluster\",nodename=~\"$node\"}",
     "legendFormat": " {{resource_id}} - {{cluster}}/{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk IO Read Rate by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 40 },
   "yaxes": [
    { "format": "Bps", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pks_heapster_node_disk_io_read_bytes{cluster=~\"$cluster\",nodename=~\"$node\"}[10m])) by (cluster, nodename)",
     "legendFormat": "{{cluster}}/{{nodename}}"
    }
   ]
  }
 ]
}