{
 "title": "PKS Overview",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_node_info, cluster_name)"
   },
   {
    "name": "node",
    "query": "label_values(kube_node_info{cluster_name=~\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_info{cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Namespaces Active",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{cluster_name=~\"$cluster\", phase=\"Active\"})"
    }
   ]
  },
  {
   "title": "Namespaces Terminating",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_namespace_status_phase{cluster_name=~\"$cluster\", phase=\"Terminating\"})"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster_name=~\"$cluster\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster_name=~\"$cluster\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster_name=~\"$cluster\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Containers Running",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Restarts of Containers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_deployment_created{cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_service_created{cluster_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pks_heapster_cluster_memory_usage{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Max Node Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kubernetes_node_memory_working_set_bytes{cluster_name=~\"$cluster\", node_name=~\"$node\"} / kubernetes_node_memory_available_bytes{cluster_name=~\"$cluster\", node_name=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Max Node CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kubernetes_node_cpu_usage_nanocores{cluster_name=~\"$cluster\", node_name=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Max Node Storage Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pks_heapster_node_filesystem_usage{cluster=~\"$cluster\", nodename=~\"$node\"} / pks_heapster_node_filesystem_limit{cluster=~\"$cluster\", nodename=~\"$node\"})"
    }
   ]
  }
 ]
}