{
 "title": "PKS Pod",
 "tags": [
  "k8s",
  "pks"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_node_info, cluster_name)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{cluster_name=~\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{cluster_name=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Rate By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "rate(kubernetes_pod_container_cpu_usage_nanocores{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubernetes_pod_container_memory_usage_bytes{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Pods Available in Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", condition=\"true\"}) by (cluster_name, namespace)",
     "legendFormat": "{{namespace}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Pods Unavailable in Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", condition=\"false\"}) by (cluster_name, namespace)",
     "legendFormat": "{{namespace}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Running\"}) by (cluster_name, namespace, pod)",
     "legendFormat": "{{pod}}/{{namespace}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Failed\"}) by (cluster_name, namespace, pod)",
     "legendFormat": "{{pod}}/{{namespace}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Pending\"}) by (cluster_name, namespace, pod)",
     "legendFormat": "{{pod}}/{{namespace}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Succeeded\"}) by (cluster_name, namespace, pod)",
     "legendFormat": "{{pod}}/{{namespace}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Memory Page Faults Rate By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "page faults / sec" }
   ],
   "targets": [
    {
     "expr": "rate(kubernetes_pod_container_memory_page_faults{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes Received Rate By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_rx_bytes{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes Transferred Rate By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_tx_bytes{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}/{{namespace_name}}/{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Networking Errors By Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kubernetes_pod_network_rx_errors{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "rx_err - {{pod_name}}/{{namespace_name}}/{{cluster_name}}"
    },
    {
     "expr": "rate(kubernetes_pod_network_tx_errors{cluster_name=~\"$cluster\", namespace=~\"$namespace\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "tx_err - {{pod_name}}/{{namespace_name}}/{{cluster_name}}"
    }
   ]
  }
 ]
}